packages: 
  board: !include packages/board_d1_mini.yaml
  base_components: !include packages/esp_home_components.yaml

binary_sensor:
  - name: "${pretty_name} Button 1"
    platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: homeassistant.turn_on
          data: 
            entity_id: "${target_1}"
  - name: "${pretty_name} Button 2"
    platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: homeassistant.turn_off
          data: 
            entity_id: "${target_1}"
