packages: 
  board: !include packages/board_esp01_1m.yaml
  base_components: !include packages/esp_home_components.yaml

# Need to turn off the serial logger because we are using the serial
# connection for the power sensors.
logger:
  baud_rate: 0
  level: DEBUG

uart:
  rx_pin: RX
  baud_rate: 4800

status_led:
  pin:
    number: 13
    inverted: True

binary_sensor:
  - name: "${pretty_name} Button"
    platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: light_1
  - platform: status
    name: "${pretty_name} Status"

output:
  - platform: gpio
    pin:
      number: 12
      inverted: False
    id: relay_1

light:
  - platform: binary
    name: "${ui_name}"
    id: light_1
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: cse7766
    current:
      name: "${pretty_name} Current"
    voltage:
      name: "${pretty_name} Voltage"
    power:
      name: "${pretty_name} Power"
    update_interval: 10s
