packages: 
  package: !include packages/treatlife_ss01s_base.yaml

binary_sensor:
  - name: "${pretty_name} Button"
    platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - switch.toggle: relay_1

switch:
  - name: "${ui_name}"
    id: relay_1
    icon: "${icon}"
    platform: gpio
    pin:
      number: 12
      inverted: False
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - switch.turn_on: power_led
    on_turn_off:
      - switch.turn_off: power_led
