# adapted from https://community.home-assistant.io/t/esphome-compatible-3-way-light-switches/159360/38
packages: 
  board: !include packages/board_esp01_1m.yaml
  base_components: !include packages/esp_home_components.yaml

status_led:
  pin:
    number: GPIO5  # Red LED
    inverted: True

binary_sensor:
  - platform: gpio
    id: button
    name: "${pretty_name} Button"
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

  - platform: gpio
    id: power_sensor
    pin:
      number: GPIO14
      inverted: True
    filters:
      - delayed_off: 50ms
    on_press:
      - light.turn_off: white_led
    on_release:
      - light.turn_on: white_led

output:
  - platform: gpio
    id: white_led_output
    pin:
      number: GPIO4
      inverted: True

light:
  - platform: binary
    id: white_led
    output: white_led_output
    restore_mode: RESTORE_DEFAULT_ON

switch:
  - platform: gpio
    id: relay
    pin: GPIO12
  - platform: template
    id: the_switch
    name: "${ui_name}"
    icon: "${icon}"
    lambda: |-
      if (id(power_sensor).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            binary_sensor.is_off: power_sensor
          then:
            - switch.toggle: relay
    turn_off_action:
      - if:
          condition:
            binary_sensor.is_on: power_sensor
          then:
            - switch.toggle: relay
