captive_portal:

# Enable logging
logger:

ota:

web_server:
  port: 80

api:

packages:
  wifi: !include wifi.yaml
  wifi_signal: !include wifi_signal.yaml
  uptime: !include uptime.yaml

switch:
  - platform: restart
    name: "${pretty_name} Restart"
